language: clojure
clojure:
- 1.9.0
script: lein test && lein uberjar
addons:
  artifacts:
    working_dir: target
    paths:
    - $(ls *standalone.jar | tr "\n" ":")
    - $(ls target/*standalone.jar | tr "\n" ":")
    target_paths:
    - "/kafka-http-reporter/$TRAVIS_BRANCH"
notifications:
  slack:
    secure: T3TtvfbEIO/369wZCAk2sPKsvvIkR1Jq5zTI9oLCLeRDr0LnWm+iPBWWpQ1k/Hkn29tukeOLgPj0/9Oq0dPd9Wj2krmmv7OSirveaWC1+s8C1CYhEpzc2JWKYuHFwbyWOIXkyRl+mUEhZOdgCAP74WRm1DT7cH4U7zJIuuqxFhU8l1rEfuosmQUAWSy+d9rh7CErCQCH7/W9ST/x2z0wolZv4bsYMWRP0A16zUJMySSTqNDI3FidCnfpv+QVLsvsYAqMyxjY44Mkxp92W6oBcelJkc40T447x2eQywdtMSV3jWnBq/8tuTzvj+nBu4KG2DdjdihuOhQKpb6Zz3CvivPj+pC8QelYILx0bYwkZt6ku5CdsSgc5MFY2hWAIQNYyUOr6zHzcNlut56NQ7CLg95BVx4266OvYNoJWC1zX8c4Jc3YtrbteYj2MXyB6ZZXejA1304SNza8Ma8h4utMh1a221Tin3wUTCvyzCGLBuuXrTWi4JwXrnuEtHlMmov2EiMP/zAmj4RpADKfDMZfEKrHjYnnnlVIzg8gQJi0xakC5SHyd36gxL5eSpmvhJKrG0kh6J7HOx/bACXQS4Oj3UbV8b9XeDhOWeWSdoj7Ld9787EHO7d+h/D2ElEdxOJDsfBsXXP25S/XR0YpXOl1vwbbV5OEav7D/G3d61dXj/g=
deploy:
  provider: releases
  api_key:
    secure: t4+Eu6/PJnH+fcZ/37FvccP7JysvxnWJkQNZcGih1U0bnKTcuSP4hvYUI1rVzjJrSqUc8+tqjE5D4iKRLj25wKUx5GsRziVTBMPKDrmgdFSgm39Bl+iN/iFpjhBWfm2SS/+ySigkQpyoet6YbOcfFD4OxMEaSTfblFW8RMuL6gyJ3QaZGY3UihoEGCjwOLj5XsX5NubgUXh0saXicGHfXLgjQi8J1wFMtB+VjKZk0OQDSCHJ4MtEAuONWqNJG++D8hyrWKbNOXJC9spilrvW741Felyq+2IKmxIFAXq4crfbPz7U4sr6V3AZ8CLS99GG1flKeXK6iV6UkOUav8lVyyVnnRjnbf4LT9WUqqBxUvrG/pUBv1Z+ScoRUZcPhSgZa6hrtgyBJdv2Olakdeatl4k5Wud59zQ75q4tn1X6Cl4eGcR8NVMUFfm+XF8dbwUHd8jG2G4ZA2ttoT38/iIEmd7yz13I4zpw0ERATjv7hHxYIcMGPIFpsXqeDS70D6D3luU8yFCUi2MU7CXt+aAdZw0amAVwpECB6a9AIJgib2I3VHCIx6oaEbJlg1WGBrs3hFYriW/WYOy+yb27Pb4pgQs+TxTfpUYzs1JQEhw033wWHHuz2bMBSbp7rJe3HOn2QI/WEu+IG657OAcseyM5+/ZCL46MCptuam/bCf8XPN8=
  file_glob: true
  file: target/*-standalone.jar
  skip_cleanup: true
  on:
    tags: true
